### BAGIAN PRODUK
GET http://127.0.0.1:5000/produk

###
GET http://127.0.0.1:5000/produk/2

###
POST http://127.0.0.1:5000/produk
Content-Type: application/json

{
    "nama":"laptop Msi",
    "kategori":"Elektronik",
    "harga":12000.00,
    "stok":4
} 

###
PUT http://127.0.0.1:5000/produk/9
Content-Type: application/json

{
    "nama":"Laptop MSI",
    "kategori":"Elektronik",
    "harga":60000.0,
    "stok":5,
    "id_produk":9

}

###
DELETE http://127.0.0.1:5000/produk/8



### BAGIAN PELANGGAN
GET http://127.0.0.1:5000/pelanggan

###
GET http://127.0.0.1:5000/pelanggan/3

###
POST http://127.0.0.1:5000/pelanggan
Content-Type: application/json

{
    "nama":"kelvin",
    "alamat":"tanjung pinang,kuantan",
    "telepon": "0812754199"

}

###
PUT http://127.0.0.1:5000/pelanggan/5
Content-Type: application/json

{
    "nama":"kelvin Dwi Putra",
    "alamat":"Batam indah no 4",
    "telepon":"08127541",
    "id_pelanggan":5

}

###
DELETE http://127.0.0.1:5000/pelanggan/11



### BAGIAN TRANSAKSI
GET http://127.0.0.1:5000/transaksi

###
GET http://127.0.0.1:5000/transaksi/1

###
POST http://127.0.0.1:5000/transaksi
Content-Type: application/json

{
    "id_pelanggan":5 ,
        "tanggal":"2024-06-17"


}

###
PUT http://127.0.0.1:5000/transaksi/1
Content-Type: application/json

{
    "id_pelanggan":1,
    "tanggal":"2024-05-17"


}

###
#DELETE  http://127.0.0.1:5000/transaksi/3

### BAGIAN DETAIL TRANSAKSI
GET http://127.0.0.1:5000/detail

###
GET http://127.0.0.1:5000/detail/1

###
POST http://127.0.0.1:5000/detail
Content-Type: application/json

{
    "id_transaksi":2,
    "id_produk":3,
    "jumlah":3,
    "harga":100.0,
    "total":300.0,
    "sub_total":300.00,
    "metode_pembayaran":"cash"




}

###
PUT http://127.0.0.1:5000/detail/5
Content-Type: application/json

{
    "id_transaksi":2,
    "id_produk":3,
    "jumlah":3,
    "harga":100.0,
    "total":300.0,
    "sub_total":300.00,
    "metode_pembayaran":"credit-card",
    "id_detail":5


}

###
DELETE http://127.0.0.1:5000/detail/5